services:
  - type: web
    name: yt-creator-tools
    env: python
    region: frankfurt
    plan: free
    buildCommand: |
      curl -fsSL https://deno.land/install.sh | sh
      export DENO_INSTALL="/opt/render/.deno"
      export PATH="$DENO_INSTALL/bin:$PATH"
      pip install -r api/requirements.txt
    startCommand: |
      export DENO_INSTALL="/opt/render/.deno"
      export PATH="$DENO_INSTALL/bin:$PATH"
      gunicorn -w 4 -b 0.0.0.0:$PORT api.app:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        generateValue: true
      - key: DENO_INSTALL
        value: /opt/render/.deno
