#!/usr/bin/env python3
"""
Script de test local pour vérifier que l'API fonctionne
Exécutez : python test_local.py
"""

import sys
import os

# Ajouter le dossier api au path
sys.path.insert(0, os.path.join(os.path.dirname(__file__), 'api'))

from subtitles import get_subtitles, get_available_languages, SubtitleError

def test_video_id(video_id):
    """Teste l'extraction de sous-titres pour un ID vidéo"""
    print(f"\n{'='*60}")
    print(f"Test de la vidéo : {video_id}")
    print(f"{'='*60}\n")
    
    # Test 1 : Langues disponibles
    print("🔍 Récupération des langues disponibles...")
    try:
        languages = get_available_languages(video_id)
        print(f"✅ {len(languages)} langue(s) trouvée(s):")
        # Afficher seulement les 5 premières pour éviter le spam
        for lang in languages[:5]:
            auto = " (Auto-généré)" if lang['isAutoGenerated'] else ""
            print(f"   - {lang['name']} ({lang['code']}){auto}")
        if len(languages) > 5:
            print(f"   ... et {len(languages) - 5} autres langues")
    except SubtitleError as e:
        print(f"❌ Erreur : {e}")
        return False
    
    print()
    
    # IMPORTANT : Attendre entre chaque requête pour éviter le rate limiting
    import time
    time.sleep(2)
    
    # Test 2 : Extraction TXT
    print("📄 Test format TXT...")
    try:
        result = get_subtitles(video_id, 'txt', 'fr')
        preview = result['content'][:200] + "..." if len(result['content']) > 200 else result['content']
        print(f"✅ TXT récupéré ({len(result['content'])} caractères)")
        print(f"   Aperçu : {preview}")
        print(f"   Langue : {result['language']}")
    except SubtitleError as e:
        print(f"❌ Erreur TXT : {e}")
    
    print()
    time.sleep(2)  # Attendre encore
    
    # Test 3 : Extraction SRT (optionnel, commenté pour éviter rate limit)
    # print("🎬 Test format SRT...")
    # try:
    #     result = get_subtitles(video_id, 'srt', 'fr')
    #     lines = result['content'].split('\n')[:10]
    #     print(f"✅ SRT récupéré ({result['lineCount']} lignes)")
    # except SubtitleError as e:
    #     print(f"❌ Erreur SRT : {e}")
    
    return True

def main():
    """Fonction principale"""
    print("\n" + "="*60)
    print("🧪 TEST DE L'API SOUS-TITRES YOUTUBE")
    print("="*60)
    
    # Vidéos de test - RÉDUITES pour éviter le rate limiting
    test_videos = [
        {
            'id': '0ZZ6WpkoAww',
            'name': 'Votre vidéo de test'
        }
    ]
    
    success_count = 0
    
    for video in test_videos:
        if test_video_id(video['id']):
            success_count += 1
    
    # Résumé
    print(f"\n{'='*60}")
    print(f"📊 RÉSUMÉ DES TESTS")
    print(f"{'='*60}")
    print(f"✅ Succès : {success_count}/{len(test_videos)}")
    print(f"❌ Échecs : {len(test_videos) - success_count}/{len(test_videos)}")
    
    if success_count == len(test_videos):
        print("\n🎉 Tous les tests ont réussi ! Prêt pour le déploiement.")
        return 0
    else:
        print("\n⚠️  Certains tests ont échoué. Vérifiez les erreurs ci-dessus.")
        return 1

if __name__ == '__main__':
    exit(main())