from flask import Flask, request, jsonify, send_from_directory
from flask_cors import CORS
import os

# Créer l'application Flask ici
app = Flask(__name__, static_folder='..', static_url_path='')

# Configuration CORS
CORS(app, resources={
    r"/api/*": {
        "origins": "*",
        "methods": ["GET", "POST", "OPTIONS"],
        "allow_headers": ["Content-Type"]
    }
})

# Route pour servir les fichiers statiques
@app.route('/')
def serve_index():
    return send_from_directory('..', 'index.html')

@app.route('/<path:path>')
def serve_static(path):
    return send_from_directory('..', path)

# Route santé
@app.route('/api/health', methods=['GET'])
def health_check():
    return jsonify({
        'status': 'ok',
        'service': 'YT Creator Tools API',
        'version': '2.0.0'
    }), 200

# Import des fonctions de sous-titres APRÈS la création de l'app
try:
    from subtitles import get_subtitles, SubtitleError
    from subtitles_fallback import get_subtitles_fallback
except ImportError as e:
    print(f"Warning: Some subtitle modules not available: {e}")

# Route principale pour récupérer les sous-titres
@app.route('/api/subtitles', methods=['POST', 'OPTIONS'])
def get_video_subtitles():
    if request.method == 'OPTIONS':
        return '', 200
    
    try:
        data = request.get_json()
        
        if not data:
            return jsonify({'error': 'Corps de requête manquant'}), 400
        
        video_id = data.get('videoId')
        format_type = data.get('format', 'txt')
        language = data.get('language', 'fr')
        
        if not video_id:
            return jsonify({'error': 'videoId manquant'}), 400
        
        valid_formats = ['txt', 'srt', 'vtt']
        if format_type not in valid_formats:
            return jsonify({
                'error': f'Format invalide. Formats acceptés: {", ".join(valid_formats)}'
            }), 400
        
        # ESSAYER D'ABORD LA MÉTHODE FALLBACK (plus fiable sur Render)
        try:
            result = get_subtitles_fallback(video_id, format_type, language)
            return jsonify(result), 200
            
        except Exception as fallback_error:
            # Fallback sur yt-dlp seulement si disponible
            try:
                result = get_subtitles(video_id, format_type, language)
                return jsonify(result), 200
            except Exception as e:
                # Les deux méthodes ont échoué
                return jsonify({
                    'error': f'Impossible de récupérer les sous-titres: {str(fallback_error)}'
                }), 404
    
    except Exception as e:
        print(f"Erreur serveur: {e}")
        return jsonify({
            'error': 'Erreur interne du serveur',
            'details': str(e) if os.getenv('FLASK_ENV') == 'development' else None
        }), 500

# Route pour lister les langues disponibles
@app.route('/api/subtitles/languages/<video_id>', methods=['GET'])
def get_available_languages(video_id):
    try:
        # Pour simplifier, retourner les langues principales
        languages = [
            {'code': 'fr', 'name': 'Français', 'isAutoGenerated': True},
            {'code': 'en', 'name': 'English', 'isAutoGenerated': True},
        ]
        return jsonify({
            'videoId': video_id,
            'languages': languages
        }), 200
    
    except Exception as e:
        return jsonify({
            'error': 'Erreur lors de la récupération des langues',
            'details': str(e)
        }), 500

# Gestion des erreurs
@app.errorhandler(404)
def not_found(error):
    return jsonify({'error': 'Route non trouvée'}), 404

@app.errorhandler(500)
def internal_error(error):
    return jsonify({'error': 'Erreur interne du serveur'}), 500

if __name__ == '__main__':
    port = int(os.environ.get('PORT', 5000))
    debug = os.environ.get('FLASK_ENV') == 'development'
    app.run(host='0.0.0.0', port=port, debug=debug)