import yt_dlp
import re
import json
import os
import tempfile
import urllib.request
import xml.etree.ElementTree as ET

print("\u2705 Module subtitles charg\u00e9 avec support cookies")


class SubtitleError(Exception):
    """Exception personnalis\u00e9e pour les erreurs de sous-titres"""
    pass


# ==================== COOKIES ====================

def setup_cookies():
    """Configure les cookies YouTube depuis les variables d'environnement ou fichiers."""
    cookies_env = os.getenv('YOUTUBE_COOKIES')
    if cookies_env:
        try:
            with tempfile.NamedTemporaryFile(mode='w', suffix='.txt', delete=False) as f:
                f.write(cookies_env)
                cookies_path = f.name
            print(f"\u2705 Cookies charg\u00e9s depuis variable d'environnement: {cookies_path}")
            return cookies_path
        except Exception as e:
            print(f"\u274c Erreur cr\u00e9ation fichier cookies: {e}")

    for candidate in ['cookies.txt', os.path.join(os.path.dirname(__file__), 'cookies.txt')]:
        if os.path.exists(candidate):
            print(f"\u2705 Cookies trouv\u00e9s: {candidate}")
            return candidate

    return None


# ==================== OPTIONS DE BASE ====================

def get_ydl_base_opts():
    """
    Options yt-dlp communes (2026).
    - android_vr  : client principal, sans PO Token requis
    - web_embedded: fallback pour la majorit\u00e9 des vid\u00e9os publiques
    Avec Deno install\u00e9 (render.yaml), tous les formats sont disponibles.
    """
    opts = {
        'skip_download': True,
        'quiet': True,
        'no_warnings': True,
        'socket_timeout': 30,
        'extractor_args': {
            'youtube': {
                'player_client': ['android_vr', 'web_embedded'],
            }
        },
    }

    deno_paths = [
        '/opt/render/.deno/bin/deno',
        os.path.expanduser('~/.deno/bin/deno'),
        '/usr/local/bin/deno',
        '/usr/bin/deno',
    ]
    for deno_path in deno_paths:
        if os.path.isfile(deno_path):
            opts['js_runtimes'] = {'deno': {'path': deno_path}}
            print(f"\u2705 Deno d\u00e9tect\u00e9: {deno_path}")
            break

    return opts


# ==================== LANGUES ====================

def get_available_languages(video_id):
    """R\u00e9cup\u00e8re la liste des langues de sous-titres disponibles."""
    print(f"\U0001f50d Recherche des langues disponibles pour: {video_id}")
    try:
        url = f'https://www.youtube.com/watch?v={video_id}'
        ydl_opts = get_ydl_base_opts()

        cookies_file = setup_cookies()
        if cookies_file:
            ydl_opts['cookiefile'] = cookies_file

        with yt_dlp.YoutubeDL(ydl_opts) as ydl:
            info = ydl.extract_info(url, download=False)

        subtitles = info.get('subtitles', {})
        automatic_captions = info.get('automatic_captions', {})

        if not subtitles and not automatic_captions:
            raise SubtitleError('Aucun sous-titre disponible pour cette vid\u00e9o')

        languages = []

        for lang in subtitles.keys():
            languages.append({
                'code': lang,
                'name': lang.upper(),
                'isAutoGenerated': False,
                'isTranslatable': True
            })

        for lang in automatic_captions.keys():
            if lang not in subtitles:
                languages.append({
                    'code': lang,
                    'name': f"{lang.upper()} (Auto)",
                    'isAutoGenerated': True,
                    'isTranslatable': True
                })

        print(f"\u2705 {len(languages)} langues trouv\u00e9es")
        return languages

    except SubtitleError:
        raise
    except yt_dlp.utils.DownloadError as e:
        error_msg = str(e)
        if 'Sign in to confirm' in error_msg:
            raise SubtitleError('Blocage anti-bot d\u00e9tect\u00e9 - cookies requis')
        if 'Video unavailable' in error_msg:
            raise SubtitleError('Vid\u00e9o non disponible')
        raise SubtitleError(f'Erreur yt-dlp : {error_msg}')
    except Exception as e:
        raise SubtitleError(f'Erreur inattendue : {type(e).__name__} - {str(e)}')


# ==================== SOUS-TITRES ====================

def get_subtitles(video_id, format_type='txt', language='fr'):
    """
    R\u00e9cup\u00e8re et formate les sous-titres d'une vid\u00e9o YouTube.

    Args:
        video_id   : ID YouTube (ex: 'dQw4w9WgXcQ')
        format_type: 'txt', 'srt' ou 'vtt'
        language   : code langue (ex: 'fr', 'en')

    Returns:
        dict avec 'content', 'language', 'format', 'lineCount', 'isAutoGenerated'
    """
    print(f"\U0001f3af Demande de sous-titres avec cookies: {video_id}")

    try:
        url = f'https://www.youtube.com/watch?v={video_id}'
        ydl_opts = get_ydl_base_opts()
        ydl_opts.update({
            'writesubtitles': True,
            'writeautomaticsub': True,
            'subtitleslangs': [language, 'fr', 'en'],
            'extract_flat': False,
        })

        cookies_file = setup_cookies()
        if cookies_file:
            ydl_opts['cookiefile'] = cookies_file
            print(f"\u2705 Utilisation des cookies: {cookies_file}")
        else:
            print("\u26a0\ufe0f  Aucun cookie disponible - mode sans authentification")

        with yt_dlp.YoutubeDL(ydl_opts) as ydl:
            info = ydl.extract_info(url, download=False)

        subtitles = info.get('subtitles', {})
        automatic_captions = info.get('automatic_captions', {})
        all_subs = {**automatic_captions, **subtitles}

        if not all_subs:
            raise SubtitleError('Aucun sous-titre disponible pour cette vid\u00e9o')

        # S\u00e9lection de la langue
        selected_lang = None
        is_auto = False
        subtitle_data = None

        for lang in [language, 'fr', 'en']:
            if lang in subtitles:
                selected_lang, subtitle_data, is_auto = lang, subtitles[lang], False
                break
            if lang in automatic_captions:
                selected_lang, subtitle_data, is_auto = lang, automatic_captions[lang], True
                break

        if not selected_lang:
            selected_lang = list(all_subs.keys())[0]
            subtitle_data = all_subs[selected_lang]
            is_auto = selected_lang in automatic_captions

        if not subtitle_data:
            raise SubtitleError('Donn\u00e9es de sous-titres vides pour cette langue')

        # Meilleur format disponible
        chosen_fmt = None
        for preferred_ext in ['json3', 'srv1', 'vtt', 'ttml']:
            for fmt in subtitle_data:
                if fmt.get('ext') == preferred_ext:
                    chosen_fmt = fmt
                    break
            if chosen_fmt:
                break
        if not chosen_fmt:
            chosen_fmt = subtitle_data[0]

        print(f"\U0001f4e5 T\u00e9l\u00e9chargement [{selected_lang}] format [{chosen_fmt.get('ext')}]")

        # T\u00e9l\u00e9chargement
        try:
            req = urllib.request.Request(
                chosen_fmt['url'],
                headers={'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'}
            )
            response = urllib.request.urlopen(req, timeout=15)
            raw_content = response.read().decode('utf-8')
        except Exception as e:
            raise SubtitleError(f'Impossible de t\u00e9l\u00e9charger le fichier de sous-titres : {e}')

        # Parsing
        transcript_data = []
        ext = chosen_fmt.get('ext', '')

        if ext == 'json3' or raw_content.strip().startswith('{'):
            try:
                transcript_data = parse_youtube_json(json.loads(raw_content))
            except Exception as e:
                print(f"\u26a0\ufe0f  Parsing JSON3 \u00e9chou\u00e9 ({e}), tentative XML...")

        if not transcript_data:
            transcript_data = parse_xml_subtitles(raw_content)

        if not transcript_data:
            raise SubtitleError('Impossible de parser le contenu des sous-titres')

        print(f"\u2705 {len(transcript_data)} segments pars\u00e9s")

        # Formatage
        if format_type == 'srt':
            content = format_as_srt(transcript_data)
        elif format_type == 'vtt':
            content = format_as_vtt(transcript_data)
        else:
            content = format_as_text(transcript_data)

        return {
            'videoId': video_id,
            'language': selected_lang,
            'format': format_type,
            'content': content,
            'lineCount': len(transcript_data),
            'isAutoGenerated': is_auto,
            'method': 'yt-dlp_2026'
        }

    except yt_dlp.utils.DownloadError as e:
        error_msg = str(e)
        if 'Video unavailable' in error_msg:
            raise SubtitleError('Vid\u00e9o non disponible')
        if 'Sign in to confirm' in error_msg:
            raise SubtitleError('Blocage anti-bot d\u00e9tect\u00e9 - cookies n\u00e9cessaires')
        if 'Requested format is not available' in error_msg:
            raise SubtitleError('Aucun format de sous-titres disponible pour cette vid\u00e9o')
        raise SubtitleError(f'Erreur yt-dlp : {error_msg}')

    except SubtitleError:
        raise

    except Exception as e:
        import traceback
        print(f"\u274c Erreur inattendue:\n{traceback.format_exc()}")
        raise SubtitleError(f'Erreur : {type(e).__name__} - {str(e)}')


# ==================== PARSEURS ====================

def parse_youtube_json(json_data):
    """Parse le format JSON3 natif de YouTube."""
    transcript = []
    try:
        for event in json_data.get('events', []):
            if 'segs' not in event:
                continue
            start = event.get('tStartMs', 0) / 1000.0
            duration = event.get('dDurationMs', 0) / 1000.0
            text = ''.join(seg.get('utf8', '') for seg in event['segs']).strip()
            if text and text != '\n':
                transcript.append({'text': text, 'start': start, 'duration': duration})
    except Exception as e:
        print(f"\u26a0\ufe0f  Erreur parse JSON3 : {e}")
    return transcript


def parse_xml_subtitles(xml_content):
    """Parse les formats XML/srv1/ttml de YouTube."""
    transcript = []
    try:
        xml_content = (xml_content.strip()
                       .replace('&amp;', '&').replace('&lt;', '<')
                       .replace('&gt;', '>').replace('&quot;', '"'). replace('&#39;', "'"))
        try:
            root = ET.fromstring(xml_content)
        except ET.ParseError as e:
            print(f"\u26a0\ufe0f  XML parse error ({e}), tentative VTT...")
            return parse_vtt_fallback(xml_content)

        for element in root.iter():
            tag = element.tag.split('}')[1] if '}' in element.tag else element.tag
            if tag not in ('text', 'p'):
                continue

            text = re.sub(r'<[^>]+>', '', ''.join(element.itertext())).strip()
            if not text:
                continue

            start = 0.0
            duration = 2.0

            if element.get('start') is not None:
                start = float(element.get('start', 0))
            elif element.get('t') is not None:
                start = float(element.get('t', 0)) / 1000.0

            if element.get('dur') is not None:
                duration = float(element.get('dur', 2))
            elif element.get('d') is not None:
                duration = float(element.get('d', 2000)) / 1000.0

            transcript.append({'text': text, 'start': start, 'duration': duration})

    except Exception as e:
        print(f"\u26a0\ufe0f  Erreur parse XML : {e}")
        transcript = parse_vtt_fallback(xml_content)

    return transcript


def parse_vtt_fallback(content):
    """Dernier recours : parse un WebVTT brut avec regex."""
    transcript = []
    try:
        pattern = re.compile(
            r'(\d{1,2}:\d{2}:\d{2}[.,]\d{3})\s*-->\s*(\d{1,2}:\d{2}:\d{2}[.,]\d{3})\s*\n(.*?)(?=\n\n|\Z)',
            re.DOTALL
        )
        for match in pattern.finditer(content):
            start_str, end_str, text = match.groups()
            text = re.sub(r'<[^>]+>', '', text).strip()
            if text:
                s = parse_timestamp(start_str)
                e = parse_timestamp(end_str)
                transcript.append({'text': text, 'start': s, 'duration': max(0.0, e - s)})
    except Exception as e:
        print(f"\u26a0\ufe0f  Erreur parse VTT fallback : {e}")
    return transcript


def parse_timestamp(ts_str):
    """Convertit HH:MM:SS,mmm ou HH:MM:SS.mmm en secondes."""
    try:
        parts = ts_str.replace(',', '.').split(':')
        if len(parts) == 3:
            return int(parts[0]) * 3600 + int(parts[1]) * 60 + float(parts[2])
        if len(parts) == 2:
            return int(parts[0]) * 60 + float(parts[1])
    except Exception:
        pass
    return 0.0


# ==================== FORMATEURS ====================

def format_as_text(transcript_data):
    """Texte brut lisible."""
    parts = [re.sub(r'\[.*?\]', '', e['text']).strip() for e in transcript_data]
    parts = [p for p in parts if p]
    full = re.sub(r'([.!?])\s+', r'\1\n\n', ' '.join(parts))
    return full.strip()


def format_as_srt(transcript_data):
    """Format SRT standard."""
    lines = []
    for i, entry in enumerate(transcript_data, start=1):
        s = format_ts_srt(entry['start'])
        e = format_ts_srt(entry['start'] + entry['duration'])
        lines += [str(i), f"{s} --> {e}", entry['text'].strip(), '']
    return '\n'.join(lines)


def format_as_vtt(transcript_data):
    """Format WebVTT."""
    lines = ['WEBVTT', '']
    for entry in transcript_data:
        s = format_ts_vtt(entry['start'])
        e = format_ts_vtt(entry['start'] + entry['duration'])
        lines += [f"{s} --> {e}", entry['text'].strip(), '']
    return '\n'.join(lines)


def format_ts_srt(seconds):
    h, rem = divmod(int(seconds), 3600)
    m, s = divmod(rem, 60)
    ms = int((seconds % 1) * 1000)
    return f"{h:02d}:{m:02d}:{s:02d},{ms:03d}"


def format_ts_vtt(seconds):
    h, rem = divmod(int(seconds), 3600)
    m, s = divmod(rem, 60)
    ms = int((seconds % 1) * 1000)
    return f"{h:02d}:{m:02d}:{s:02d}.{ms:03d}"
